### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by MatadorProBr** [StarGate01/AmongUs-Mumble#1]
I was a little confused to make the mod work, I managed to do everything right except the part I couldn't
put the winhttp.dll file in the game folder, because when it opened it gave an error, please make a video explaining how to download the mod and make it work, if you do I will thank you very much.

**Comment by StarGate01** [comment]
I'll consider making a video. In the meantime, try to access your game files this way: 
 - Right-click on "Among Us" in your Steam library list
 - Click "Properties"
 - Select the tab "Local files"
 - Click "Browse local files"
 - A file manager window should open at `C:\Steam\steamapps\common\Among Us` or similar.
 - Put the `winhttp.dll` file into this directory

**Comment by MatadorProBr** [comment]
Thanks, now it's working fine, now I can play with my friends :)

**Comment by StarGate01** [comment]
Glad to hear that! Let me know when you encounter any other issues.
