### ISSUE TITLE
Add some kind of heartbeat

### ISSUE THREAD

**Issue by StarGate01** [StarGate01/AmongUs-Mumble#10]
Add keepalive signal to show the user position capture is working

**Comment by StarGate01** [comment]
@alisenai Port over the heartbeat from your fork maybe? I found that to be useful to check if the mod actually works. Maybe make it optional (`verbose` output in the config)

**Comment by alisenai** [comment]
This will come with the [https://github.com/StarGate01/AmongUs-Mumble/tree/logging-system](logging-system) branch when it is merged in. (It made for a good test case).

Considering only printing the position if it has _changed_ as to prevent repeated printing of the same position.

**Comment by StarGate01** [comment]
Good call on the change detection.

Another feature request was to make the frequency of the heartbeat configurable.

Another one was to always use the same line for the position (Could be done using the `\r` control char).

**Comment by alisenai** [comment]
Added position change detection when printing. Logging system currently supports disabling console with `-n`,`--no-console`.  
See 950b7b95e8b6aed52678434a7bfd1edec2306606.

Will add more config options soon. Still looking into same-line printing for the position.
