### ISSUE TITLE
Add option to isolate ghosts

### ISSUE THREAD

**Issue by StarGate01** [StarGate01/AmongUs-Mumble#11]
Add option to choose between
 -  Isolated ghost channel using different mumble context, ghosts can talk to each other regardless of position, ghosts can only listen in meetings
 -  One channel for all, ghosts always muted, ghosts can listen to players they are nearby and to meetings

**Comment by StarGate01** [comment]
Third option:
 - Different channel for ghosts, but they can talk to each other using positional audio

Does that make sense though?

**Comment by alisenai** [comment]
Seems like the same thing as: Isolate ghosts using a different Mumble context, but positional audio still enabled.
Wouldn't know how to approach this without more Mumble API/RPC.
Correct me if I'm wrong.

The idea could become a 3rd option for sure.

**Comment by LelouBil** [comment]
Unfortunately, the context cannot be used if they are in the same channel
https://wiki.mumble.info/wiki/Link
> The context string is used to determine which users on a Mumble server should hear each other positionally. If context between two Mumble users does not match the positional audio the data is stripped server-side and voice will be received as non-positional.

They will just be heard non positionally

**Comment by StarGate01** [comment]
From #21 :

> If someone doesn't have the same context or any context set, they will just hear/be heard non positionally.

That's unfortunate. I wonder why they included the context in the first place, when all you have to do to disable positional audio is to set the player position to exactly (0, 0, 0). My guess would be for server side moderation scripts, which move players to different channels depending on context. In the long term we could look into this, [MuMo](https://wiki.mumble.info/wiki/Mumo) seem to be the tool of choice. Alternatively, the new Mumble 1.4 RPC API seem to support switching channels as well.

So for the next release, what options should we provide? I propose to have a config option to choose between:

 - My old implementation (Ghosts can eavesdrop on alive players but not talk)
 - Aliens implementation (Ghosts can always talk to each other, but cant listen to alive players)

In both implementations, the behaviour during meetings would be that ghosts can listen but not talk. I'm open to suggestions.

**Comment by alisenai** [comment]
Ah, I misunderstood the purpose of the context then. I'm happy with just the two, but there's always the "trick" of adding an impossible offset to the ghost's base position. 
For example:
Ghost 1 Base Position (-1, +2)
Ghost 2 Base Position (+5, -3)
New Ghost 1 Position: (-1 + OFFSET, +2 + OFFSET)
New Ghost 2 Position: (+5 + OFFSET, -3 + OFFSET)
Were OFFSET is an impossible position to be in.

"Relativeness" (distance between the two) of ghost's positions would be maintained while players would be too far to hear.
This is more of a hack than a solution, but I think it's worth considering.

**Comment by StarGate01** [comment]
The offset is a great idea. We should add that.

Essentially we will replace the context with a section of the world that is larger than the map.

**Comment by StarGate01** [comment]
Implemented as of ecfc39c7d65918e03aa0b3e91312584cc3099a0a...867babf52f54b147569c5383ee961bc89ce202b1
