### ISSUE TITLE
Look into GitHub Actions testing.

### ISSUE THREAD

**Issue by alisenai** [StarGate01/AmongUs-Mumble#17]

**Comment by StarGate01** [comment]
Do you want to work on this? Also what would we test for?

**Comment by alisenai** [comment]
@StarGate01 Just would like to make sure anything on the main branch compiles. Testing would be harder.

Might not be worth the trouble if the master <- dev <- feature branch workflow is done correctly.

**Comment by StarGate01** [comment]
Not really possible atm without a lot of work (setting up steam, decompiler, msvc ... in a container)
