### ISSUE TITLE
Look into automated deobfuscation

### ISSUE THREAD

**Issue by LelouBil** [StarGate01/AmongUs-Mumble#19]
Basically we could use [Roslyn ](https://github.com/dotnet/roslyn) to analyze the c# prototypes of Il2CppInspector and guess classes using known members/nested classes/methods.

It looks feasible.

**Comment by StarGate01** [comment]
Yes, I thought about that too. Id say implement it as an external tool.

**Comment by StarGate01** [comment]
I also made a python tool for dynamic analysis, check the wiki.

**Comment by StarGate01** [comment]
Xref: #34
