### ISSUE TITLE
Among Us Lost Link

### ISSUE THREAD

**Issue by Augmaa** [StarGate01/AmongUs-Mumble#2]
We have all the paths set to the right thing and connected to mumble.
When we launch our game it says Among Us linked and then a few seconds later among us lost link.
![image](https://user-images.githubusercontent.com/74216800/98607376-0dc05480-22b7-11eb-85b9-2ab15699f020.png)
![image](https://user-images.githubusercontent.com/74216800/98607390-14e76280-22b7-11eb-917c-bc779f8a22df.png)

**Comment by StarGate01** [comment]
Yes, this happens sometimes. It should reconnect as soon as you join a lobby and move around.

Also: Are you sure your exe path of `A:Files\mumble.exe` is correct?

**Comment by neptunesblade** [comment]
This can also occur when not using version `v2020.10.22s` - make sure you're not using the beta version. It will link, then unlink ~5 seconds later.
