### ISSUE TITLE
No proximity files or line of code when among us opens

### ISSUE THREAD

**Issue by yuhvet** [StarGate01/AmongUs-Mumble#30]
At first, whenever I dragged in the winhttp file it would not let me open among us at all. I then made a new certificate wizard and imported the file. Once that was done I opened up among us and it finally opened, but the line of codes tab that is supposed to open up along with among us doesn't open. I also noticed my friends have proximityconfig and proximitylog files in their local among us files, but I don't seem to have those. Mumble does not work when I have everything set up correctly, even when it's supposed to automatically undeafen me, it does not. I don't know anyone else who has had this problem. Any fix?

**Comment by StarGate01** [comment]
Thank you for your report. This sounds like a usage problem, if you want to get support via chat, you can join out Discord server here: https://discord.gg/4UkHEJ5sqg and get help in #need-help .

Otherwise, please write what exact version of the game and mod you are using.

**Comment by StarGate01** [comment]
(For future reference) Resolved: VsRedist2015 was missing - get it from https://www.microsoft.com/en-us/download/details.aspx?id=48145
