### ISSUE TITLE
Add documentation about the different ghost voice modes from the config

### ISSUE THREAD

**Issue by AlexejheroYTB** [StarGate01/AmongUs-Mumble#33]
```
; Set ghost voice mode
; 0 = Purgatory
; 1 = Spectate
; 2 = Haunt
ghost-voice-mode=0
```

**Comment by alisenai** [comment]
@AlexejheroYTB 
I believe the updated documentation for this is planned for the next release (1.0.0.6) but, for now, here they are:
- Purgatory: Users talk to other ghosts with full volume. 
- Spectate: Can listen to players with proximity but can not talk.
- Haunt: Can listen and talk to players with proximity.

Please note that, with the current build, all players will have to _manually_ sync their configs to the same values, or else gameplay elements may not function as intended.

**Comment by AlexejheroYTB** [comment]
Does Purgatory allow ghosts to hear alive players' proximity chat?

**Comment by alisenai** [comment]
@AlexejheroYTB It does not, no, except durring meetings where ghosts are muted.

**Comment by StarGate01** [comment]
Next version will have it in the README: https://github.com/StarGate01/AmongUs-Mumble/tree/dev#main-features
