### ISSUE TITLE
Support Linux / Proton

### ISSUE THREAD

**Issue by StarGate01** [StarGate01/AmongUs-Mumble#4]

**Comment by StarGate01** [comment]
Use `start /unix /usr/bin/mumble rpc foobar` to send an rpc command from wine to the linux host which runs mumble.

Use `/dev/shm` instead of `OpenFileMappingW` for shared memory, see https://github.com/feilen/oculus-wine-wrapper/blob/master/oculus_shm_adapter.c

**Comment by StarGate01** [comment]
Detecting wine: https://www.winehq.org/pipermail/wine-devel/2008-September/069387.html

**Comment by StarGate01** [comment]
Test on Linux 8Steam, Proton) shows that after installing vcrun2015 using protontricks and adding a few DLL overrides,
 - Console works
 - Injection works
 - Hooking works

Bugs:
 - Crash on console minimization

However, the function `ucrtbase.dll.strtold` (called via `api-ms-win-crt-convert-l1-1-0` via `std::stold`), used at [CLI11.hpp#L1500](https://github.com/StarGate01/AmongUs-Mumble/blob/master/AUMInjector/user/CLI11.hpp#L1500) requires Wine >=5.19, see https://www.winehq.org/announce/5.19 and https://bugs.winehq.org/show_bug.cgi?id=49873.

Until Steam releases a Proton version containing Wine >=5.19 (Currently 5.13-2), we can temporarily comment the offending function in CLI11, as we don't use it at all (It parses floating point numbers of type `long double`, we don't use those).

**Comment by 1337god** [comment]
It just crashes in the latest version after following the instructions

**Comment by StarGate01** [comment]
Yes. The latest versions of the game/mod were not (yet) ported to the wine branch.

**Comment by StarGate01** [comment]
As of dcb2a0de91baf20cc1aef33db6adbf39c482fe02, the wine version nuw support the mumble link (make sure to set the `wine-uid` config option to your linux user uid). Still not working: Mumble RPC, DirectX overlay.

**Comment by 1337god** [comment]
> As of [dcb2a0d](https://github.com/StarGate01/AmongUs-Mumble/commit/dcb2a0de91baf20cc1aef33db6adbf39c482fe02), the wine version now support the mumble link (make sure to set the `wine-uid` config option to your linux user uid). Still not working: Mumble RPC, DirectX overlay.

Thank you! Will update

**Comment by Corben78** [comment]
Hey there, I just read that you have to compile the wine branch on your own. Is that possible to do on Linux? Haven't seen a makefile, so I'm wondering.

**Comment by StarGate01** [comment]
Hi, unfortunately we do not have a build setup for Linux at the moment. The DLL that is being compiled is still a Windows NT DLL, it just runs in Wine / Steam Proton. 

However, we plan to merge (beta) Linux support in the next release, so stay tuned!

**Comment by StarGate01** [comment]
Wine support is now merged into dev. See https://github.com/StarGate01/AmongUs-Mumble/wiki/Installation-and-Setup for updated installation instructions and known issues.

**Comment by StarGate01** [comment]
Live in version 1.0.0.14 :)
