### ISSUE TITLE
Allow ghosts to talk when in haunt mode

### ISSUE THREAD

**Issue by NotHappyxd** [StarGate01/AmongUs-Mumble#41]
**Is your feature request related to a problem? Please describe.**
When your in haunt mode, you can't talk to other ghosts. 

**Describe the solution you'd like**
Allow you to talk to ghosts when your in haunt mode.

**Describe alternatives you've considered**

**Additional context**

**Comment by alisenai** [comment]
You should be able to talk to other ghosts while in haunt mode currently.
This will have to be tested.

**Comment by StarGate01** [comment]
Please provide additional info: Does communication work proximity based? In haunt mode, ghosts can only talk to each other when they are close to each other.

**Comment by NotHappyxd** [comment]
I think its just me then. I was in haunt mode with another ghost in close proximity but we still couldn't hear each other and we weren't mute on mumble..

**Comment by alisenai** [comment]
Is this a consistent issue or a one-time occurrence? This may have been a settings sync issue - a disagreement of ghost modes between clients.

**Comment by StarGate01** [comment]
Also, if you would like to get help via chat, please join #need-help in our Discord server.

**Comment by StarGate01** [comment]
Please update to 1.0.0.10 and try again.
