### ISSUE TITLE
Since the update to v2020.11.17s it does not work

### ISSUE THREAD

**Issue by vanaart** [StarGate01/AmongUs-Mumble#45]
**Description**
Since the update to v2020.11.17s it does not work

**Steps To Reproduce**
1. Updated AmongUs to v2020.11.17s
2. Download the latest release of the plugin V1.0.0.8
3. Started a game, but the gui is not loaded and the position is not being transferred to Mumble

**Expected behavior**
That the plugin is being loaded into AmongUs and work

**Game version**
v2020.11.17s

**Additional context**

**Comment by alisenai** [comment]
The game had another update recently. This is being fixed currently.

**Comment by alisenai** [comment]
This should be fixed with f2a493d65959e2dad494c0b8f7c10e50d1cdcf69.

**Comment by vanaart** [comment]
It's working again. Playing it right now :D
