### ISSUE TITLE
The link is not made correctly.

### ISSUE THREAD

**Issue by ItsMeHoppy** [StarGate01/AmongUs-Mumble#46]
**Description**
Hello,
After Among Us and Mumble are linked, a few seconds later they lose connection between the two.

**Steps To Reproduce**
1. Launch Mumble.
2. Launch Among Us.
3. Wait for the connection and disconnection of the link in the Mumble log.

**Expected behavior**
The link does not disconnect.

**Game version**
v2020.11.17s
dll: 1.0.0.8

**Additional context**
ProximityLog: https://pastebin.com/CX4xgCDU
Mumble Log: https://i.imgur.com/Ytuk1Fl.png

**Comment by alisenai** [comment]
See #45, this is likely related.
Among Us got a new update and didn't update the game version. We are working on a fix currently.

**Comment by StarGate01** [comment]
Please update to 1.0.0.9 and report back.

**Comment by ItsMeHoppy** [comment]
It works now, thanks for your work!
