### ISSUE TITLE
Lobby host + some players getting banned from lobby 

### ISSUE THREAD

**Issue by dodoit1991** [StarGate01/AmongUs-Mumble#49]
**Description**
Lobby host + some players getting banned from lobby 

**Steps To Reproduce**
After playing a game with the mod, the lobby host and some of the players get banned, everytime. 

**Game version**
1.0.0.9 | 202011171

**Comment by StarGate01** [comment]
Thank you for the report. We are looking into this, Innersloth seems to have ramped up chat spam detection. 
Internally we use hidden chat messages for settings sync.

**Comment by StarGate01** [comment]
This should be fixed in version 1.0.0.10, I implemented a new network protocol which does not depend on chat messages.

Please update and try again.

**Comment by dodoit1991** [comment]
It hasn't been completly fixed, it doesnt happen everytime, but still sometimes.

**Comment by StarGate01** [comment]
That is very strange. Are you able to isolate when it happens? Do you use any other mods?

**Comment by dodoit1991** [comment]
This is the only mod we use, and when it happens about every 3 rounds it immediately happens to a few of us. I will try to pay attention to it next time we play to see if I can isolate when it happens.

**Comment by StarGate01** [comment]
Thank you. Please make sure that everyone in the lobby uses the new version.

**Comment by dodoit1991** [comment]
We did check that, but next time I will double check to be sure!

**Comment by JackofSpades707** [comment]
I can confirm that this happens even if everyone in the lobby is on 10.0.0.10, but it doesn't seem to have consistent behavior.
Sometimes it happens a couple of games in a row, sometimes we get a bunch of games in before it happens.

It doesn't happen to everyone, but when it does happen, it seems to happen to the host the most often

**Comment by StarGate01** [comment]
Okay, thank you for the reports. We will continue to investigate this issue, first step for me is to reproduce it. Unfortunately the server cheat-detection is a (rightfully) well-kept secret by Innersloth.
