### ISSUE TITLE
One player not getting muted when comms are called

### ISSUE THREAD

**Issue by higps** [StarGate01/AmongUs-Mumble#53]
In our group of 9 one player with identical settings to all the rest of us was not muted when comms were called, but regular proximity and directional worked

**Comment by alisenai** [comment]
You can ask them to check if their mumble path is set correctly in their config. It should be the path to where they have it installed, not necessarily the same as everyone else. If it's set correctly, there have been a few instances where Mumble's RPC won't mute the user - not sure why this occurs.

This will likely be fixed with #52 when we have more control over mumble or with positional isolation that is planned for in the future.

**Comment by higps** [comment]
This used to work for this player, as he has identical settings to the rest, and everything else works besides the mute when comms are called. We tried different usernames and such, but it still only happened to him out of all 9 players.

**Comment by higps** [comment]
The same issue happened again, but now with a different player. We tried restarting, but the same player always didn't get muted when comms were called, and could talk while he was a ghost.

Restarting client, server didn't help. Exact same issue as last time, but with a different player, the previous player no longer has the issue.

Is this ping related somehow? I run the murmur server on my local machine, and we're all in the EU, while he was in the US, and we play on the North America servers

**Comment by StarGate01** [comment]
It should not be ping related, the sabotage event happens locally and does not require network communication.

The main problem I could see is that the Mumble RPC call somehow fails or times out. We will continue to investigate this. Are there any interesting things in the log files? Does the log file for they player where it did not work record the sabotage event?

**Comment by higps** [comment]
[ProximityLog-Everything working.txt](https://github.com/StarGate01/AmongUs-Mumble/files/5705420/ProximityLog-Everything.working.txt)
[ProximityLog-Not muted when dead or when comms are sabotaged.txt](https://github.com/StarGate01/AmongUs-Mumble/files/5705421/ProximityLog-Not.muted.when.dead.or.when.comms.are.sabotaged.txt)

I've attached two log files, one where the user has the issue of not being muted when comms are sabotaged or when dead as a ghost. but proximity works otherwise. The other log is from my pc where everything is working properly.

**Comment by StarGate01** [comment]
Thank you for the log files. It seems that the sabotage events are cought correctly on both PCs, which leads me to believe that something with the Mumble RPC call is not working, just like when the Mumble path is incorrect. But there seems to be something else wrong. We'll keep that on our agends.

**Comment by higps** [comment]
@StarGate01 we've found the issue to be related to using bluetooth headsets

**Comment by StarGate01** [comment]
Thank you for the report. This will now be tracked in #81
