### ISSUE TITLE
Where is the config file?

### ISSUE THREAD

**Issue by Doubl4r** [StarGate01/AmongUs-Mumble#58]
So I have the mumble directory in another disk, you said I have to change it in the config file, where is that config file and how is it called? Thanks

**Comment by StarGate01** [comment]
Hi! Don't worry about visibility, rest assured that we read every issue, it just might take a few hours because of timezones.

Concerning your issue, the configuration file will be automatically created when you start the game with the mod installed for the first time.

**Comment by Doubl4r** [comment]
Okay, thanks!
