### ISSUE TITLE
Implement differentiation between multiple lobbies in the same voice channel

### ISSUE THREAD

**Issue by StarGate01** [StarGate01/AmongUs-Mumble#6]

**Comment by StarGate01** [comment]
Do we actually need this? Mumble provides as is a practically unlimited amount of channels.

**Comment by alisenai** [comment]
Will probably confuse users (can't hear anything / can hear everyone / everyone can hear them). Also an issue if two groups of people in the same channel are trying starting a game.

Channels already solve this problem, as you say, but don't solve the issue of random players joining in during an active game. Maybe some form of channel locking (would require mumble API)? I don't see any good implementation for this though. 

Could just be outside of the scope for this program.

**Comment by StarGate01** [comment]
Yes, agree on out of scope. The mumble devs told me that mumble 1.4 will probably come with a full fledged RPC capable plugin API, maybe then well look at this again.
