### ISSUE TITLE
Add config file

### ISSUE THREAD

**Issue by StarGate01** [StarGate01/AmongUs-Mumble#7]
Overridable by CLI arguments

**Comment by StarGate01** [comment]
Use CLI11 for this

**Comment by alisenai** [comment]
Possibly a YAML-like config. Simple key : value storage.

**Comment by StarGate01** [comment]
The library we already use for command line parsing, CLI11, also supports reading config files in TOML or INI format. The library internally manages the merging of cli arguments and config file entries.

See: https://github.com/CLIUtils/CLI11/blob/master/README.md#configuration-file

**Comment by alisenai** [comment]
I see, it does both. That's the way to go then.

Great reference as well.

**Comment by StarGate01** [comment]
By default, the file `config.ini` is loaded if it exists. The current configuration is printed at game start. Commadn line arguments take precedence over the config file.
