### ISSUE TITLE
Failed, Virus Detected

### ISSUE THREAD

**Issue by NaterEST** [StarGate01/AmongUs-Mumble#73]
So, I and some other people are having an issue where they can't download the latest file for mumble proximity chat, because windows says that there might be a virus and deletes the program immediately. Maybe we can fix it ourselves, or it's a small issue in the code or something like that.
Welcomes, Nate.

**Comment by Croos3r** [comment]
Have this warning too on the same file.

**Comment by StarGate01** [comment]
Thank you for your report, unfortunately there is not much we as developers can do. Virus-detection is a well kept secret (understandably) - in addition, we *do* employ some low-level tricks which maybe is also used by some malware, thus producing a false-positive.

You could either restore the file from quarantine (should be easy in windows defender) and add an exception, or you could try to compile the cody yourself.

**Comment by NaterEST** [comment]
Thank you for answering. I myself am not good at coding (still a newbie), but I just know about these things. I have Windows Defender and I just needed to turn off real-time protection, for the file to work. The false-positive thing should work, if done correctly.

**Comment by StarGate01** [comment]
Happy to see it works, but I do not recommend outright turning off real-time protection. Instead, you should add a single exception and keep the rest of the protection enabled.

Sorry for the inconvenience!

**Comment by NaterEST** [comment]
I added the exception, works fine.
