### ISSUE TITLE
Latest version bug 

### ISSUE THREAD

**Issue by Snorfold** [StarGate01/AmongUs-Mumble#74]
I have install the latest version but when i cut communication the voice dont stop and we cant speak by the camera :/

**Comment by StarGate01** [comment]
I dont quite understand your scenario. Are you exiting the game? Mumble still continues to run independently of the game, by design.

**Comment by alisenai** [comment]
Are you referring to sabotaging communications and speaking in the observation room? The first should work, but it should be noted that the latter isn't currently implemented.

**Comment by StarGate01** [comment]
It has been 2 weeks, closing.
