### ISSUE TITLE
It works.... but it doesn't?!??

### ISSUE THREAD

**Issue by KikachuHope** [StarGate01/AmongUs-Mumble#75]
**Description**
We have a group of people setting up Mumble and Prox chat for the first time, We all did it at the same time following all the steps. 

We get into a lobby, The fade works for some people and not others. 
4 people could walk away and their voices would fade and mute like normal.... but three people could walk away and a few could still hear them across the map/lobby
But then for other people it would work properly. 

**Steps To Reproduce**
Your guess is as good as mine honestly. 

**Expected behavior**
The fade out and distance to work as intended

**Game version**
We are using the most recent version as of 12/28/2020

**Comment by alisenai** [comment]
**General Problems:**
- Are you updated to the latest version of the game and mod? Check again (Top-left of the main menu).
- Make sure you unzip/extract the download to get the `winhttp.dll` file.
- Make sure you didn't rename `winhttp.dll` - It needs to be called EXACTLY that.
- Did you put `winhttp.dll` in the same folder as Among Us.exe?'

**Mumble-Related Problems:**
- Did you enable `Link to Game and Transmit Position` under Configure > Settings > Plugins?
- Did you enable `Link v1.2` under Configure > Settings > Plugins?
- Did you enable `Positional Audio` under Configure > Settings > Audio Output?
- If using a Bluetooth headset, try using a different headset.
- Do you have mumble installed to: `C:\Program Files\Mumble\mumble.exe`? If not, edit the `proximityconfig.ini`.
- Are you in the same mumble channel and same lobby/game?
- Make sure your icon changes color in mumble when you speak.

The issues listed above fix the vast majority of user problems.

If these common fixes did not help or if you would like more support, please head over to the `#need-help` channel in our Discord: 
https://discord.gg/4UkHEJ5sqg

**Comment by KikachuHope** [comment]
Hello! It seems to have been the issue with the Bluetooth headset! Thank you so much!
