### ISSUE TITLE
Among us proximity chat

### ISSUE THREAD

**Issue by braden371** [StarGate01/AmongUs-Mumble#78]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alisenai** [comment]
This issue doesn't provide any information. I will be closing it if no information is provided. Feel free to edit the issue or comment on it.

**Comment by alisenai** [comment]
It has been a few days with no additional info provided - closing. 

Feel free to re-open or create a new issue if you would like to.
