### ISSUE TITLE
Question about Linux installation

### ISSUE THREAD

**Issue by bauer-alex** [StarGate01/AmongUs-Mumble#87]
**Description**
First of all thanks for the Linux support. You guys are da best! :D
I followed all setup instructions given in [Installation and Setup](https://github.com/StarGate01/AmongUs-Mumble/wiki/Installation-and-Setup). The last step is to add the installed path (`which mumble`) to `ProximityConfig.ini`.
My only problem is that I don't know how to install the package on Linux (in my case: Ubuntu 20.10). I downloaded the [newest release](https://github.com/StarGate01/AmongUs-Mumble/releases/) and thought it'd be possible to use `make install` to install it (as e.g. outlined [here](https://www.itprotoday.com/development-techniques-and-management/how-install-targz-file-ubuntu-linux)), but that didn't work, maybe because the package is meant to be installed in a different way on Linux?

If relevant, the answer might also be very helpful to add as a note to [Installation and Setup](https://github.com/StarGate01/AmongUs-Mumble/wiki/Installation-and-Setup).

**Additional context**
I'm not the most proficient Linux user, so sorry if that's a more trivial question.

**Comment by StarGate01** [comment]
Hi, installing the Mumble client on Ubuntu is as easy as executing `sudo apt-get install mumble`. 

However, the installation instructions for Linux / Proton are a bit out of date, I'll fix them up in the next days. There might also be a few issues with new versions of Proton or vcredist, stay tuned.

**Comment by bauer-alex** [comment]
Thanks for the quick feedback!
The installation of Mumble did work now, and Mumble connects to Among Us when the game is started. However, I don't see the `Proximity Configuration` button in the top of the main menu in Among Us, and Proximity Chat doesn't seem to work (using Ubuntu 20.10 and Proton 5.0).

Before writing an extensive bug report, I'll just wait for you to update the installation instructions and try it again based on these.
Thanks in advance!

**Comment by StarGate01** [comment]
Okay, I verified the latest version on my Linux system (5.4.112.1-Manjaro). I added a few details to the installation instructions (https://github.com/StarGate01/AmongUs-Mumble/wiki/Installation-and-Setup#linux).

Please note that Linux support is not as good as Windows support. For example, the graphical in-game overlay does not work (yet) due to the DirectX emulation that is used. See https://github.com/StarGate01/AmongUs-Mumble/wiki/Installation-and-Setup#known-linux-specific-issues for more details.

Your Linux Mumble client still prints "Among Us linked" if the mod connects, and auto-muting and unmuting is also noticeable. Of course, you can also just check the logfile of the mod (`ProximityLog.txt`).

**Comment by bauer-alex** [comment]
Nice!
Now I also got it running. :)

One thing I was unsure about was whether I'd need to create my own Mumble server for playing. This is always necessary, right?
In this regard, maybe you could link to [guildbit.com](https://guildbit.com/), which seems a legit site for creating temporary Mumble servers for free.

Apart from that, feel free to close this issue.

**Comment by StarGate01** [comment]
Glad to hear you got it working!

Enabling the users to host their own servers was a conscious design decision. This way, users are able to build a federated network, which reduces hosting costs for us and increases security and privacy for the users.

We do host a public Mumble server for the community which is free to use, for more info check our Discord server (https://discord.gg/4UkHEJ5sqg).
